<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue'
import {ElMessage} from 'element-plus'
import {http,type ApiResponse} from '../api/http'
import {hasPermission} from '../auth'
import ConsultationSection from '../components/discharge/ConsultationSection.vue'
import FollowUpSection from '../components/discharge/FollowUpSection.vue'
interface Row{id:number;encounterId:number;inpatientNo:string;admissionTimes:number;patientName:string;gender:string|null;departmentName:string|null;primaryDiagnosis:string|null;doctorName:string|null;admittedAt:string|null;plannedDischargeAt:string|null;actualDischargeAt:string|null;latestOutpatientAppointmentAt:string|null;outpatientArrived:boolean|null;outpatientArrivalAt:string|null;outpatientReporter:string|null;outpatientNoShowReason:string|null;latestNutritionAppointmentAt:string|null;latestHomeRehabAppointmentAt:string|null;latestFollowUpAt:string|null;status:string;abnormalCodes:string[];abnormalReason:string|null;specialPatient:boolean;specialReason:string|null;followUpRequired:boolean|null;followUpDay7:string|null;followUpDay30:string|null;followUpDay60:string|null;followUpDetailsJson:string|null}
interface FollowUpDetail{day:number;followUpAt:string;executorName:string;recoveryCondition:string;remindOutpatient:boolean;homeRehabEvaluation:string;homeRehabUnsatisfiedReason:string;homeRehabAssessmentAt:string;nutritionEvaluation:string;nutritionUnsatisfiedReason:string;nutritionAssessmentAt:string}
interface Page<T>{items:T[];total:number;page:number;pageSize:number}
interface Summary{inpatientCount:number;plannedCount:number;nutritionPatientCount:number;nutritionRecordCount:number;homeRehabPatientCount:number;homeRehabRecordCount:number;outpatientPatientCount:number}
interface Department{id:number;departmentName:string}
interface HistoryItem{id:number;operatorName:string;operatedAt:string;actionType:string;beforeData:string|null;afterData:string|null}
const rows=ref<Row[]>([]),total=ref(0),summary=ref<Summary>(),departments=ref<Department[]>([]),loading=ref(false),summaryLoading=ref(false),uploading=ref(false),saving=ref(false),detailLoading=ref(false),historyLoading=ref(false),dialog=ref(false),current=ref<Row|null>(null),historyItems=ref<HistoryItem[]>([]),page=ref(1),pageSize=ref(50),keyword=ref(''),departmentId=ref<number>(),timeType=ref(''),discharged=ref<boolean>(),dateRange=ref<string[]>([])
const emptyFollowUp=(day:number,legacy=''):FollowUpDetail=>({day,followUpAt:'',executorName:'',recoveryCondition:legacy,remindOutpatient:false,homeRehabEvaluation:'',homeRehabUnsatisfiedReason:'',homeRehabAssessmentAt:'',nutritionEvaluation:'',nutritionUnsatisfiedReason:'',nutritionAssessmentAt:''})
const form=reactive({plannedDischargeAt:'',specialPatient:false,specialReason:'',abnormalReason:'',outpatientAppointmentAt:'',outpatientArrived:undefined as boolean|undefined,outpatientArrivalAt:'',outpatientReporter:'',outpatientNoShowReason:'',followUpRequired:true,followUpDay7:'',followUpDay30:'',followUpDay60:'',followUpDetails:[emptyFollowUp(7),emptyFollowUp(30),emptyFollowUp(60)] as FollowUpDetail[]})
const canAttending=computed(()=>hasPermission('PERM_FIELD_ATTENDING_DOCTOR')),canOutpatient=computed(()=>hasPermission('PERM_FIELD_OUTPATIENT')),canNutrition=computed(()=>hasPermission('PERM_FIELD_NUTRITION')),canHomeRehab=computed(()=>hasPermission('PERM_FIELD_HOME_REHAB')),canFollowUp=computed(()=>hasPermission('PERM_FIELD_FOLLOW_UP'))
const canSaveRecord=computed(()=>canAttending.value||canOutpatient.value||canFollowUp.value)
const timeTypes=[['OUTPATIENT','预约复诊时间'],['NUTRITION','预约营养会诊时间'],['HOME_REHAB','预约居家康复时间'],['FOLLOW_UP','随访时间']] as const
const abnormalLabels:Record<string,string>={LATE_PLAN:'出院前12小时内填报',MISSING_PLAN:'未填报预计出院时间',DATE_MISMATCH:'预计与实际出院日期不一致'}
const addDay=(value:string)=>{const d=new Date(`${value}T00:00:00+08:00`);d.setDate(d.getDate()+1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const baseParams=computed(()=>({keyword:keyword.value.trim()||undefined,departmentId:departmentId.value,timeType:timeType.value||undefined,startAt:dateRange.value?.[0]?`${dateRange.value[0]}T00:00:00+08:00`:undefined,endAt:dateRange.value?.[1]?`${addDay(dateRange.value[1])}T00:00:00+08:00`:undefined,discharged:discharged.value}))
const load=async()=>{loading.value=true;try{const data=(await http.get<ApiResponse<Page<Row>>>('/discharge/records',{params:{...baseParams.value,page:page.value,pageSize:pageSize.value}})).data.data;rows.value=data.items;total.value=data.total}catch(e){ElMessage.error(e instanceof Error?e.message:'列表加载失败')}finally{loading.value=false}}
const loadSummary=async()=>{summaryLoading.value=true;try{summary.value=(await http.get<ApiResponse<Summary>>('/discharge/records/summary',{params:baseParams.value})).data.data}catch(e){ElMessage.error(e instanceof Error?e.message:'统计加载失败')}finally{summaryLoading.value=false}}
const loadAll=()=>Promise.all([load(),loadSummary()])
const loadDepartments=async()=>{try{departments.value=(await http.get<ApiResponse<Department[]>>('/discharge/records/filter-options')).data.data}catch(e){ElMessage.error(e instanceof Error?e.message:'科室筛选项加载失败')}}
const query=()=>{page.value=1;loadAll()}
const reset=()=>{keyword.value='';departmentId.value=undefined;timeType.value='';discharged.value=undefined;dateRange.value=[];page.value=1;loadAll()}
const beforeUpload=(file:File)=>{if(!/\.xlsx$/i.test(file.name)){ElMessage.error('仅支持 .xlsx 文件');return false}const data=new FormData();data.append('file',file);uploading.value=true;http.post('/discharge/import',data).then(()=>{ElMessage.success('导入成功');page.value=1;return loadAll()}).catch(e=>ElMessage.error(e instanceof Error?e.message:'导入失败')).finally(()=>uploading.value=false);return false}
const fillForm=(row:Row)=>{form.plannedDischargeAt=row.plannedDischargeAt||'';form.specialPatient=!!row.specialPatient;form.specialReason=row.specialReason||'';form.abnormalReason=row.abnormalReason||'';form.outpatientAppointmentAt=row.latestOutpatientAppointmentAt||'';form.outpatientArrived=row.outpatientArrived??undefined;form.outpatientArrivalAt=row.outpatientArrivalAt||'';form.outpatientReporter=row.outpatientReporter||'';form.outpatientNoShowReason=row.outpatientNoShowReason||'';form.followUpRequired=row.followUpRequired!==false;form.followUpDay7=row.followUpDay7||'';form.followUpDay30=row.followUpDay30||'';form.followUpDay60=row.followUpDay60||'';try{const parsed=JSON.parse(row.followUpDetailsJson||'[]');form.followUpDetails=Array.isArray(parsed)&&parsed.length?parsed:[emptyFollowUp(7,form.followUpDay7),emptyFollowUp(30,form.followUpDay30),emptyFollowUp(60,form.followUpDay60)]}catch{form.followUpDetails=[emptyFollowUp(7,form.followUpDay7),emptyFollowUp(30,form.followUpDay30),emptyFollowUp(60,form.followUpDay60)]}}
const edit=async(row:Row)=>{current.value=row;fillForm(row);historyItems.value=[];dialog.value=true;detailLoading.value=true;historyLoading.value=true;try{const [detailResult,historyResult]=await Promise.all([http.get<ApiResponse<Row>>(`/discharge/records/${row.id}`),http.get<ApiResponse<HistoryItem[]>>(`/discharge/records/${row.id}/history`)]);current.value=detailResult.data.data;fillForm(current.value);historyItems.value=historyResult.data.data}catch(e){ElMessage.error(e instanceof Error?e.message:'详情加载失败')}finally{detailLoading.value=false;historyLoading.value=false}}
const refreshCareData=async()=>{if(!current.value)return;await loadAll();historyLoading.value=true;try{historyItems.value=(await http.get<ApiResponse<HistoryItem[]>>(`/discharge/records/${current.value.id}/history`)).data.data}finally{historyLoading.value=false}}
const save=async()=>{if(!current.value||!canSaveRecord.value)return;if(canAttending.value&&!current.value.actualDischargeAt&&!form.plannedDischargeAt){ElMessage.warning('请填写预计出院时间');return}if(canAttending.value&&form.specialPatient&&!form.specialReason.trim()){ElMessage.warning('特殊患者必须填写特殊原因');return}if(canAttending.value&&current.value.abnormalCodes?.length&&!form.abnormalReason.trim()){ElMessage.warning('异常患者必须填写异常原因');return}if(canOutpatient.value&&form.outpatientArrived===true&&!form.outpatientArrivalAt){ElMessage.warning('已到诊患者必须填写具体到诊时间');return}if(canOutpatient.value&&form.outpatientArrived===false&&!form.outpatientNoShowReason.trim()){ElMessage.warning('未到诊患者必须填写未到诊原因');return}if(canFollowUp.value&&form.followUpDetails.some(item=>(item.homeRehabEvaluation==='不满意'&&!item.homeRehabUnsatisfiedReason.trim())||(item.nutritionEvaluation==='不满意'&&!item.nutritionUnsatisfiedReason.trim()))){ElMessage.warning('评价为不满意时必须填写原因');return}const body:Record<string,unknown>={};if(canAttending.value)Object.assign(body,{plannedDischargeAt:form.plannedDischargeAt,specialPatient:form.specialPatient,specialReason:form.specialReason.trim()||null,abnormalReason:form.abnormalReason.trim()||null});if(canOutpatient.value)Object.assign(body,{outpatientAppointmentAt:form.outpatientAppointmentAt,outpatientArrived:form.outpatientArrived,outpatientArrivalAt:form.outpatientArrivalAt,outpatientReporter:form.outpatientReporter.trim()||null,outpatientNoShowReason:form.outpatientArrived===false?form.outpatientNoShowReason.trim()||null:null});if(canFollowUp.value)Object.assign(body,{followUpRequired:form.followUpRequired,followUpDetailsJson:JSON.stringify(form.followUpDetails),followUpDay7:form.followUpDetails[0]?.recoveryCondition||null,followUpDay30:form.followUpRequired?form.followUpDetails[1]?.recoveryCondition||null:null,followUpDay60:form.followUpRequired?form.followUpDetails[2]?.recoveryCondition||null:null});saving.value=true;try{await http.put(`/discharge/records/${current.value.id}`,body);ElMessage.success('已保存');dialog.value=false;await loadAll()}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}finally{saving.value=false}}
const exportData=async()=>{try{const response=await http.get('/discharge/records/export',{params:baseParams.value,responseType:'blob'});const url=URL.createObjectURL(response.data),a=document.createElement('a');a.href=url;a.download='预出院记录.csv';a.click();URL.revokeObjectURL(url)}catch(e){ElMessage.error(e instanceof Error?e.message:'导出失败')}}
const formatTime=(value:string|null|undefined)=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—'
const isSoon=(value:string|null)=>{if(!value)return false;const diff=new Date(value).getTime()-Date.now();return diff>=0&&diff<3*86400000}
const displayStatus=(row:Row)=>row.actualDischargeAt?(row.abnormalCodes?.length?'异常':'正常'):row.status
const statusType=(row:Row)=>displayStatus(row)==='异常'?'danger':displayStatus(row)==='未填报'?'info':'success'
const abnormalText=(row:Row)=>[...(row.abnormalCodes||[]).map(code=>abnormalLabels[code]||code),...(row.abnormalReason?[row.abnormalReason]:[])].join('；')||'—'
const historyDescription=(item:HistoryItem)=>{try{const before=JSON.parse(item.beforeData||'{}'),after=JSON.parse(item.afterData||'{}'),labels:Record<string,string>={plannedDischargeAt:'预计出院时间',specialPatient:'特殊患者',specialReason:'特殊原因',abnormalReason:'异常原因',outpatientAppointmentAt:'预约复诊时间',followUpRequired:'需要回访',followUpDay7:'第7天随访',followUpDay30:'第30天随访',followUpDay60:'第60天随访'};const changes=Object.entries(labels).filter(([key])=>String(before[key]??'')!==String(after[key]??'')).map(([key,label])=>`${label}：${String(before[key]??'（空）')} → ${String(after[key]??'（空）')}`);return changes.join('；')||'更新预计出院信息'}catch{return '更新预计出院信息'}}
onMounted(()=>{loadDepartments();loadAll()})
</script>
<template><section class="page-card discharge-page">
<div class="page-heading"><div><h2>预计出院管理</h2><p>列表、统计和筛选使用相同数据范围，默认按入院时间倒序。</p></div><div class="heading-actions"><el-button v-permission="'PERM_API_DISCHARGE_EXPORT'" plain @click="exportData">导出CSV</el-button><el-upload :show-file-list="false" :before-upload="beforeUpload" accept=".xlsx"><el-button v-permission="'PERM_API_DISCHARGE_IMPORT'" type="primary" :loading="uploading">导入预出院数据</el-button></el-upload></div></div>
<div v-loading="summaryLoading" class="stat-grid discharge-stat-grid"><div><span>在院患者</span><strong>{{summary?.inpatientCount||0}} 人</strong><small>当前无实际出院时间</small></div><div><span>已填报预计出院时间</span><strong>{{summary?.plannedCount||0}} 人</strong><small>按当前筛选范围统计</small></div><div><span>预约营养会诊</span><strong>{{summary?.nutritionPatientCount||0}} 人</strong><small>共 {{summary?.nutritionRecordCount||0}} 条预约记录</small></div><div><span>预约居家康复</span><strong>{{summary?.homeRehabPatientCount||0}} 人</strong><small>共 {{summary?.homeRehabRecordCount||0}} 条预约记录</small></div><div><span>预约复诊</span><strong>{{summary?.outpatientPatientCount||0}} 人</strong><small>至少有一次复诊预约</small></div></div>
<div class="filter-bar discharge-filter-bar"><el-select v-model="departmentId" clearable placeholder="全部科室"><el-option v-for="item in departments" :key="item.id" :label="item.departmentName" :value="item.id"/></el-select><el-select v-model="timeType" clearable placeholder="时间类型（全部）"><el-option v-for="item in timeTypes" :key="item[0]" :label="item[1]" :value="item[0]"/></el-select><el-date-picker v-model="dateRange" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期" range-separator="至"/><el-select v-model="discharged" clearable placeholder="出院状态"><el-option label="未出院" :value="false"/><el-option label="已出院" :value="true"/></el-select><el-input v-model="keyword" clearable placeholder="住院号 / 姓名 / 主管医生" @keyup.enter="query"/><el-button type="primary" @click="query">查询</el-button><el-button @click="reset">重置</el-button></div>
<h3 class="table-section-title">患者预计出院情况</h3><el-table v-loading="loading" :data="rows" stripe class="discharge-table">
<el-table-column prop="patientName" label="患者姓名" width="110" fixed="left" show-overflow-tooltip/><el-table-column label="患者性别" width="90"><template #default="s">{{s.row.gender||'—'}}</template></el-table-column><el-table-column prop="inpatientNo" label="住院号" width="130" fixed="left" show-overflow-tooltip/><el-table-column prop="admissionTimes" label="住院次数" width="90" align="center"/><el-table-column label="所属科室" width="130" show-overflow-tooltip><template #default="s">{{s.row.departmentName||'—'}}</template></el-table-column><el-table-column label="入院时间" width="175"><template #default="s">{{formatTime(s.row.admittedAt)}}</template></el-table-column><el-table-column label="主诊断" min-width="170" show-overflow-tooltip><template #default="s">{{s.row.primaryDiagnosis||'—'}}</template></el-table-column><el-table-column label="主管医生" width="110" show-overflow-tooltip><template #default="s">{{s.row.doctorName||'—'}}</template></el-table-column><el-table-column label="预约复诊时间" width="175"><template #default="s">{{formatTime(s.row.latestOutpatientAppointmentAt)}}</template></el-table-column><el-table-column label="预计出院时间" width="205"><template #default="s">{{formatTime(s.row.plannedDischargeAt)}} <el-tag v-if="isSoon(s.row.plannedDischargeAt)" type="warning" size="small">临近</el-tag></template></el-table-column><el-table-column label="实际出院时间" width="175"><template #default="s">{{formatTime(s.row.actualDischargeAt)}}</template></el-table-column><el-table-column label="预约营养会诊时间" width="180"><template #default="s">{{formatTime(s.row.latestNutritionAppointmentAt)}}</template></el-table-column><el-table-column label="预约居家康复时间" width="180"><template #default="s">{{formatTime(s.row.latestHomeRehabAppointmentAt)}}</template></el-table-column><el-table-column label="随访时间" width="175"><template #default="s">{{formatTime(s.row.latestFollowUpAt)}}</template></el-table-column><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="statusType(s.row)">{{displayStatus(s.row)}}</el-tag></template></el-table-column><el-table-column label="异常原因" min-width="240" show-overflow-tooltip><template #default="s"><span :class="{'danger-text':s.row.abnormalCodes?.length}">{{abnormalText(s.row)}}</span></template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="s"><el-button link type="primary" @click="edit(s.row)">{{canAttending||canOutpatient||canNutrition||canHomeRehab||canFollowUp?(s.row.plannedDischargeAt?'编辑':'填报'):'查看'}}</el-button></template></el-table-column>
</el-table><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :page-sizes="[20,50,100,200]" :total="total" layout="total,sizes,prev,pager,next" class="pagination" @change="loadAll"/>
<el-dialog v-model="dialog" :title="current?.plannedDischargeAt?'编辑院后管理信息':'填报预计出院时间'" width="1040px" destroy-on-close>
<div v-loading="detailLoading" class="discharge-edit-dialog">
<el-descriptions v-if="current" :column="3" border><el-descriptions-item label="患者">{{current.patientName}}</el-descriptions-item><el-descriptions-item label="住院号">{{current.inpatientNo}}</el-descriptions-item><el-descriptions-item label="住院次数">{{current.admissionTimes}}</el-descriptions-item><el-descriptions-item label="所属科室">{{current.departmentName||'—'}}</el-descriptions-item><el-descriptions-item label="主管医生">{{current.doctorName||'—'}}</el-descriptions-item><el-descriptions-item label="主诊断">{{current.primaryDiagnosis||'—'}}</el-descriptions-item></el-descriptions>
<el-alert v-if="current?.abnormalCodes?.length" type="error" :closable="false" show-icon class="discharge-abnormal-alert"><template #title>系统判定异常</template><div v-for="code in current.abnormalCodes" :key="code">{{abnormalLabels[code]||code}}</div></el-alert><el-alert v-else type="success" :closable="false" title="当前未命中出院异常规则" class="discharge-abnormal-alert"/>
<el-form label-position="top" class="dialog-form">
<section class="discharge-responsibility-section"><header><strong>主管医生填报</strong><span>预计出院与特殊患者信息</span></header>
<div class="discharge-form-grid"><el-form-item label="预计出院时间" required><el-date-picker v-model="form.plannedDischargeAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" placeholder="选择预计出院时间" :disabled="!canAttending||!!current?.actualDischargeAt" style="width:100%"/><small v-if="current?.actualDischargeAt" class="muted">患者已出院，预计出院时间不可修改</small></el-form-item><el-form-item label="患者是否为特殊患者"><el-radio-group v-model="form.specialPatient" :disabled="!canAttending"><el-radio :value="false">否</el-radio><el-radio :value="true">是</el-radio></el-radio-group></el-form-item></div>
<el-form-item v-if="form.specialPatient" label="特殊原因" required><el-input v-model="form.specialReason" type="textarea" :rows="2" maxlength="2000" show-word-limit :disabled="!canAttending"/></el-form-item>
<el-form-item v-if="current?.abnormalCodes?.length" label="异常原因" required><el-input v-model="form.abnormalReason" type="textarea" :rows="2" maxlength="2000" show-word-limit placeholder="请填写实际异常原因" :disabled="!canAttending"/></el-form-item>
</section>
<div :class="{'disabled-business-block':form.specialPatient}">
<section class="discharge-responsibility-section"><header><strong>门诊部填报</strong><span>复诊预约与到诊跟踪</span></header><div class="discharge-form-grid"><el-form-item label="预约复诊时间"><el-date-picker v-model="form.outpatientAppointmentAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" :disabled="form.specialPatient||!canOutpatient" style="width:100%"/></el-form-item><el-form-item label="是否到诊"><el-radio-group v-model="form.outpatientArrived" :disabled="form.specialPatient||!canOutpatient"><el-radio :value="true">是</el-radio><el-radio :value="false">否</el-radio></el-radio-group></el-form-item><el-form-item v-if="form.outpatientArrived" label="具体到诊时间"><el-date-picker v-model="form.outpatientArrivalAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" :disabled="form.specialPatient||!canOutpatient" style="width:100%"/></el-form-item><el-form-item label="填报人"><el-input v-model="form.outpatientReporter" :disabled="form.specialPatient||!canOutpatient"/></el-form-item><el-form-item v-if="form.outpatientArrived===false" label="未到诊原因" required><el-input v-model="form.outpatientNoShowReason" :disabled="form.specialPatient||!canOutpatient"/></el-form-item></div></section>
<ConsultationSection v-if="current" :encounter-id="current.encounterId" type="NUTRITION" :disabled="form.specialPatient||!canNutrition" @changed="refreshCareData"/>
<ConsultationSection v-if="current" :encounter-id="current.encounterId" type="HOME" :disabled="form.specialPatient||!canHomeRehab" @changed="refreshCareData"/>
<FollowUpSection v-model:follow-up-required="form.followUpRequired" v-model:details="form.followUpDetails" :disabled="form.specialPatient||!canFollowUp"/>
</div>
</el-form><section class="discharge-responsibility-section"><header><strong>操作历史</strong><span>患者业务信息全程留痕</span></header><div v-loading="historyLoading" class="history-list"><el-empty v-if="!historyLoading&&!historyItems.length" description="暂无操作历史" :image-size="60"/><el-timeline v-else><el-timeline-item v-for="item in historyItems" :key="item.id" :timestamp="formatTime(item.operatedAt)" placement="top"><strong>{{item.operatorName||'system'}}</strong><p>{{historyDescription(item)}}</p></el-timeline-item></el-timeline></div></section>
</div><template #footer><el-button :disabled="saving" @click="dialog=false">关闭</el-button><el-button v-if="canSaveRecord" type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
</section></template>
