package cn.hospital.rehab.discharge.api;
import cn.hospital.rehab.common.api.*;import cn.hospital.rehab.common.security.*;import cn.hospital.rehab.common.audit.AuditLogService;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/discharge/records")
public class DischargeController {
 private final DischargeRepository repository;private final DataScopeService scopes;private final AuditLogService audit;private final DischargeRecordHistoryService history;private final FieldPermissionService fields;
 public DischargeController(DischargeRepository repository,DataScopeService scopes,AuditLogService audit,DischargeRecordHistoryService history,FieldPermissionService fields){this.repository=repository;this.scopes=scopes;this.audit=audit;this.history=history;this.fields=fields;}
 @GetMapping public ApiResponse<PageResult<DischargeSummary>> page(Authentication auth,@RequestParam(required=false)String keyword,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)String timeType,@RequestParam(required=false)java.time.OffsetDateTime startAt,@RequestParam(required=false)java.time.OffsetDateTime endAt,@RequestParam(required=false)Boolean discharged,@RequestParam(required=false)String category,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="50")int pageSize){return ApiResponse.ok(repository.page(keyword,departmentId,timeType,startAt,endAt,discharged,category,scopes.resolve(auth),page,pageSize));}
 @GetMapping("/summary") public ApiResponse<DischargeSummaryStats> summary(Authentication auth,@RequestParam(required=false)String keyword,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)String timeType,@RequestParam(required=false)java.time.OffsetDateTime startAt,@RequestParam(required=false)java.time.OffsetDateTime endAt,@RequestParam(required=false)Boolean discharged){return ApiResponse.ok(repository.summary(keyword,departmentId,timeType,startAt,endAt,discharged,scopes.resolve(auth)));}
 @GetMapping("/filter-options") public ApiResponse<java.util.List<DischargeDepartmentOption>> filterOptions(Authentication auth){return ApiResponse.ok(repository.filterOptions(scopes.resolve(auth)));}
 @GetMapping("/{id}") public ApiResponse<DischargeSummary> detail(Authentication auth,@PathVariable long id){return ApiResponse.ok(repository.find(id,scopes.resolve(auth)));}
 @GetMapping("/{id}/history") public ApiResponse<java.util.List<DischargeRecordHistory>> history(Authentication auth,@PathVariable long id){var scope=scopes.resolve(auth);repository.find(id,scope);return ApiResponse.ok(history.list(id));}
 @PutMapping("/{id}") public ApiResponse<DischargeSummary> update(Authentication auth,HttpServletRequest http,@PathVariable long id,@Valid @RequestBody UpdateDischargeRequest request){if(request.plannedDischargeAt()!=null||request.specialPatient()!=null||request.specialReason()!=null||request.abnormalReason()!=null)fields.require(auth,"FIELD_ATTENDING_DOCTOR");if(request.outpatientAppointmentAt()!=null||request.outpatientArrived()!=null||request.outpatientArrivalAt()!=null||request.outpatientReporter()!=null||request.outpatientNoShowReason()!=null)fields.require(auth,"FIELD_OUTPATIENT");if(request.followUpRequired()!=null||request.followUpDay7()!=null||request.followUpDay30()!=null||request.followUpDay60()!=null||request.followUpDetailsJson()!=null)fields.require(auth,"FIELD_FOLLOW_UP");DataScope scope=scopes.resolve(auth);var before=repository.find(id,scope);var after=repository.update(id,request,scope);audit.record(auth,"DISCHARGE","DISCHARGE_RECORD",String.valueOf(id),"UPDATE",before,after,http.getRemoteAddr());return ApiResponse.ok(after);}
}
