package cn.hospital.rehab.arrears.api;
import cn.hospital.rehab.common.api.PageResult;import cn.hospital.rehab.common.security.DataScope;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;import java.sql.*;
@Repository public class ArrearsRecordRepository {
 private static final String FILTER_WHERE="WHERE (:key='' OR e.inpatient_no ILIKE :pattern OR e.patient_name ILIKE :pattern OR e.doctor_name_source ILIKE :pattern OR e.doctor_employee_no ILIKE :pattern) AND (:dept=0 OR e.department_id=:dept) AND (:type='' OR a.arrears_type=:type) AND (:fee='' OR e.fee_type=:fee) AND (:progress='' OR a.recovery_progress=:progress) AND (:arrears=2 OR a.in_arrears=(:arrears=1)) ";
 private final JdbcClient jdbc;public ArrearsRecordRepository(JdbcClient jdbc){this.jdbc=jdbc;}
 public PageResult<ArrearsRecordSummary> page(String keyword,Long departmentId,String arrearsType,String feeType,String recoveryProgress,Boolean inArrears,int page,int size){return page(keyword,departmentId,arrearsType,feeType,recoveryProgress,inArrears,DataScope.all(),page,size);}
 public PageResult<ArrearsRecordSummary> page(String keyword,Long departmentId,String arrearsType,String feeType,String recoveryProgress,Boolean inArrears,DataScope scope,int page,int size){return query(keyword,departmentId,arrearsType,feeType,recoveryProgress,inArrears,scope,page,size,false);}
 public PageResult<ArrearsRecordSummary> export(String keyword,Long departmentId,String arrearsType,String feeType,String recoveryProgress,Boolean inArrears,DataScope scope){return query(keyword,departmentId,arrearsType,feeType,recoveryProgress,inArrears,scope,1,20000,true);}
 private PageResult<ArrearsRecordSummary> query(String keyword,Long departmentId,String arrearsType,String feeType,String recoveryProgress,Boolean inArrears,DataScope scope,int page,int size,boolean export){
  String key=clean(keyword),type=clean(arrearsType),fee=clean(feeType),progress=clean(recoveryProgress).toUpperCase();int s=export?20000:(java.util.Set.of(20,50,100,200).contains(size)?size:50);int p=Math.max(1,page);int arrears=inArrears==null?2:(inArrears?1:0);String filter=scopeSql(scope);
  String where=FILTER_WHERE+filter;
  var q=jdbc.sql("SELECT a.*,e.inpatient_no,e.admission_times,e.patient_name,e.ward_name,e.fee_type,e.doctor_name_source,e.doctor_employee_no,e.admitted_at,e.discharged_at,d.department_name,COALESCE(op_user.display_name,op_user.login_name) last_operated_by_name FROM arrears_record a JOIN patient_encounter e ON e.id=a.encounter_id LEFT JOIN sys_department d ON d.id=e.department_id LEFT JOIN sys_user op_user ON op_user.id=a.last_operated_by "+where+" ORDER BY a.arrears_amount DESC,a.source_updated_at DESC LIMIT :limit OFFSET :offset");q=params(q,key,departmentId,type,fee,progress,arrears).param("limit",s).param("offset",(p-1)*s);q=scopeParams(q,scope);var items=q.query(this::map).list();
  var count=jdbc.sql("SELECT COUNT(*) FROM arrears_record a JOIN patient_encounter e ON e.id=a.encounter_id "+where);count=params(count,key,departmentId,type,fee,progress,arrears);count=scopeParams(count,scope);long total=count.query(Long.class).single();return new PageResult<>(items,total,p,s);
 }
 public ArrearsRecordSummaryStats summary(String keyword,Long departmentId,String arrearsType,String feeType,String recoveryProgress,Boolean inArrears,DataScope scope){String key=clean(keyword),type=clean(arrearsType),fee=clean(feeType),progress=clean(recoveryProgress).toUpperCase();int arrears=inArrears==null?2:(inArrears?1:0);String sql="SELECT COUNT(*) total_people,COUNT(*) FILTER (WHERE a.arrears_type IN ('INPATIENT','在院患者')) inpatient_people,COUNT(*) FILTER (WHERE a.arrears_type IN ('DISCHARGED_UNSETTLED','出院未结算')) discharged_unsettled_people,COUNT(*) FILTER (WHERE a.arrears_type IN ('DISCHARGED_SETTLED','出院已结算')) discharged_settled_people,COALESCE(SUM(a.arrears_amount),0) total_amount,COUNT(*) FILTER (WHERE a.recovery_progress='NOT_STARTED') uncollected_people,COUNT(*) FILTER (WHERE a.recovery_progress='LEGAL_ACTION') legal_people,MAX(a.source_updated_at) source_updated_at FROM arrears_record a JOIN patient_encounter e ON e.id=a.encounter_id "+FILTER_WHERE+scopeSql(scope);var q=jdbc.sql(sql);q=params(q,key,departmentId,type,fee,progress,arrears);q=scopeParams(q,scope);return q.query((r,n)->new ArrearsRecordSummaryStats(r.getLong("total_people"),r.getLong("inpatient_people"),r.getLong("discharged_unsettled_people"),r.getLong("discharged_settled_people"),r.getBigDecimal("total_amount"),r.getLong("uncollected_people"),r.getLong("legal_people"),r.getObject("source_updated_at",java.time.OffsetDateTime.class))).single();}
 public ArrearsFilterOptions filterOptions(DataScope scope){var departments=jdbc.sql("SELECT DISTINCT d.id,d.department_name FROM arrears_record a JOIN patient_encounter e ON e.id=a.encounter_id JOIN sys_department d ON d.id=e.department_id WHERE d.enabled=TRUE"+scopeSql(scope)+" ORDER BY d.department_name");departments=scopeParams(departments,scope);var departmentItems=departments.query((r,n)->new ArrearsFilterOptions.DepartmentOption(r.getLong("id"),r.getString("department_name"))).list();var fees=jdbc.sql("SELECT DISTINCT e.fee_type FROM arrears_record a JOIN patient_encounter e ON e.id=a.encounter_id WHERE e.fee_type IS NOT NULL AND BTRIM(e.fee_type)<>''"+scopeSql(scope)+" ORDER BY e.fee_type");fees=scopeParams(fees,scope);var feeItems=fees.query(String.class).list();var types=jdbc.sql("SELECT DISTINCT a.arrears_type FROM arrears_record a JOIN patient_encounter e ON e.id=a.encounter_id WHERE a.arrears_type IS NOT NULL AND BTRIM(a.arrears_type)<>''"+scopeSql(scope)+" ORDER BY a.arrears_type");types=scopeParams(types,scope);return new ArrearsFilterOptions(departmentItems,feeItems,types.query(String.class).list());}
 public ArrearsRecordSummary update(long id,UpdateArrearsRequest r,DataScope scope,String operatorLoginName){find(id,scope);String sql="UPDATE arrears_record a SET payment_status=:status,arrears_reason=:reason,recovery_progress=CASE WHEN :status='PAID' THEN 'PAID' WHEN :progress='' THEN COALESCE(a.previous_recovery_progress,'NOT_STARTED') ELSE :progress END,previous_recovery_progress=CASE WHEN :status='PAID' AND a.recovery_progress<>'PAID' THEN a.recovery_progress WHEN :status='UNPAID' AND :progress<>'' THEN :progress ELSE COALESCE(a.previous_recovery_progress,'NOT_STARTED') END,last_operated_by=(SELECT id FROM sys_user WHERE login_name=:operator),updated_at=CURRENT_TIMESTAMP FROM patient_encounter e WHERE a.encounter_id=e.id AND a.id=:id AND (CAST(:expectedUpdatedAt AS TIMESTAMPTZ) IS NULL OR a.updated_at=:expectedUpdatedAt)"+scopeSql(scope);String progress=r.recoveryProgress()==null?"":r.recoveryProgress();var q=jdbc.sql(sql).param("status",r.paymentStatus()).param("reason",r.arrearsReason()).param("progress",progress).param("operator",operatorLoginName).param("expectedUpdatedAt",r.expectedUpdatedAt()).param("id",id);q=scopeParams(q,scope);if(q.update()==0)throw new cn.hospital.rehab.common.api.ConcurrentUpdateException("记录已被其他人员更新，请刷新后核对再保存");return find(id);}
 public ArrearsRecordSummary find(long id,DataScope scope){var q=jdbc.sql("SELECT a.*,e.inpatient_no,e.admission_times,e.patient_name,e.ward_name,e.fee_type,e.doctor_name_source,e.doctor_employee_no,e.admitted_at,e.discharged_at,d.department_name,COALESCE(op_user.display_name,op_user.login_name) last_operated_by_name FROM arrears_record a JOIN patient_encounter e ON e.id=a.encounter_id LEFT JOIN sys_department d ON d.id=e.department_id LEFT JOIN sys_user op_user ON op_user.id=a.last_operated_by WHERE a.id=:id"+scopeSql(scope)).param("id",id);return scopeParams(q,scope).query(this::map).optional().orElseThrow(()->new org.springframework.security.access.AccessDeniedException("无权访问该患者数据"));}
 private ArrearsRecordSummary find(long id){return find(id,DataScope.all());}
 static String scopeSql(DataScope s){return " AND (:allDepartments=TRUE OR e.department_id IN (:departmentIds) OR (CAST(:doctorUserId AS BIGINT) IS NOT NULL AND e.doctor_user_id=:doctorUserId))";}
 static JdbcClient.StatementSpec scopeParams(JdbcClient.StatementSpec q,DataScope s){return q.param("allDepartments",s.allDepartments()).param("doctorUserId",s.doctorUserId()).param("departmentIds",s.departmentIds().isEmpty()?java.util.Set.of(-1L):s.departmentIds());}
 private static String clean(String value){return value==null?"":value.trim();}
 private static JdbcClient.StatementSpec params(JdbcClient.StatementSpec q,String key,Long departmentId,String type,String fee,String progress,int arrears){return q.param("key",key).param("pattern","%"+key+"%").param("dept",departmentId==null?0:departmentId).param("type",type).param("fee",fee).param("progress",progress).param("arrears",arrears);}
 private ArrearsRecordSummary map(ResultSet r,int n)throws SQLException{return new ArrearsRecordSummary(r.getLong("id"),r.getString("inpatient_no"),r.getInt("admission_times"),r.getString("patient_name"),r.getString("department_name"),r.getString("ward_name"),r.getString("fee_type"),r.getString("arrears_type"),r.getString("doctor_name_source"),r.getString("doctor_employee_no"),r.getObject("admitted_at",java.time.OffsetDateTime.class),r.getObject("discharged_at",java.time.OffsetDateTime.class),r.getBigDecimal("total_cost"),r.getBigDecimal("prepaid_amount"),r.getBigDecimal("medical_insurance_paid"),r.getBigDecimal("personal_account_paid"),r.getBigDecimal("original_required_deposit"),r.getBigDecimal("final_required_deposit"),r.getBigDecimal("deposit_difference"),r.getBigDecimal("arrears_amount"),r.getBoolean("in_arrears"),r.getString("payment_status"),r.getString("arrears_reason"),r.getString("recovery_progress"),r.getString("previous_recovery_progress"),r.getString("recovery_progress_legacy"),r.getString("last_operated_by_name"),r.getObject("source_updated_at",java.time.OffsetDateTime.class),r.getObject("updated_at",java.time.OffsetDateTime.class));}
}
