package cn.hospital.rehab.arrears.api;
import cn.hospital.rehab.common.api.*;import cn.hospital.rehab.common.security.*;import cn.hospital.rehab.common.audit.AuditLogService;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import org.springframework.http.*;
@RestController @RequestMapping("/api/arrears/records")
public class ArrearsRecordController {
 private final ArrearsRecordRepository repository;private final DataScopeService scopes;private final AuditLogService audit;private final ArrearsRecordHistoryService history;private final ArrearsExportService exporter;
 public ArrearsRecordController(ArrearsRecordRepository repository,DataScopeService scopes,AuditLogService audit,ArrearsRecordHistoryService history,ArrearsExportService exporter){this.repository=repository;this.scopes=scopes;this.audit=audit;this.history=history;this.exporter=exporter;}
 @GetMapping public ApiResponse<PageResult<ArrearsRecordSummary>> page(Authentication auth,@RequestParam(required=false)String keyword,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)String arrearsType,@RequestParam(required=false)String feeType,@RequestParam(required=false)String recoveryProgress,@RequestParam(required=false)Boolean inArrears,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="50")int pageSize){return ApiResponse.ok(repository.page(keyword,departmentId,arrearsType,feeType,recoveryProgress,inArrears,scopes.resolve(auth),page,pageSize));}
 @GetMapping("/filter-options") public ApiResponse<ArrearsFilterOptions> filterOptions(Authentication auth){return ApiResponse.ok(repository.filterOptions(scopes.resolve(auth)));}
 @GetMapping("/summary") public ApiResponse<ArrearsRecordSummaryStats> summary(Authentication auth,@RequestParam(required=false)String keyword,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)String arrearsType,@RequestParam(required=false)String feeType,@RequestParam(required=false)String recoveryProgress,@RequestParam(required=false)Boolean inArrears){return ApiResponse.ok(repository.summary(keyword,departmentId,arrearsType,feeType,recoveryProgress,inArrears,scopes.resolve(auth)));}
 @PutMapping("/{id}") public ApiResponse<ArrearsRecordSummary> update(Authentication auth,HttpServletRequest http,@PathVariable long id,@Valid @RequestBody UpdateArrearsRequest request){DataScope scope=scopes.resolve(auth);var before=repository.find(id,scope);var after=repository.update(id,request,scope,auth.getName());audit.record(auth,"ARREARS","ARREARS_RECORD",String.valueOf(id),"UPDATE",before,after,http.getRemoteAddr());return ApiResponse.ok(after);}
 @GetMapping("/{id}/history") public ApiResponse<java.util.List<ArrearsRecordHistory>> history(Authentication auth,@PathVariable long id){repository.find(id,scopes.resolve(auth));return ApiResponse.ok(history.list(id));}
 @GetMapping("/export") public ResponseEntity<byte[]> export(Authentication auth,HttpServletRequest http,@RequestParam(defaultValue="csv")String format,@RequestParam(required=false)String keyword,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)String arrearsType,@RequestParam(required=false)String feeType,@RequestParam(required=false)String recoveryProgress,@RequestParam(required=false)Boolean inArrears){var p=repository.export(keyword,departmentId,arrearsType,feeType,recoveryProgress,inArrears,scopes.resolve(auth));var file=exporter.create(format,p.items(),p.total());audit.record(auth,"ARREARS","ARREARS_EXPORT",file.format(),"EXPORT",null,java.util.Map.of("rows",p.items().size(),"format",file.format()),http.getRemoteAddr());return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,file.contentDisposition()).contentType(file.mediaType()).body(file.content());}
}
